server:
  port: 8080
wx-config:
  appId: wxe62e23fb218a44d8
  appSecret: b24cc60279dffd6e3e2c898f4647e7e2
  checkToken: ***********

chatgpt-config:
  model: text-davinci-003
  temperature: 0.9
  maxTokens: 512
  apiKey: ***********
